import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Términos y Condiciones", description: "Términos que regulan el acceso y uso de la plataforma educativa CursoCapital.", alternates: { canonical: "/terms" }, openGraph: { title: "Términos y Condiciones | CursoCapital", description: "Condiciones de uso de los servicios educativos de CursoCapital." } };

export default function TermsPage() { return <LegalPage title="Términos y Condiciones" description="Estos términos constituyen un acuerdo vinculante entre tú y CursoCapital respecto del acceso y uso de la plataforma, sus cursos y servicios.">
  <section><h2>1. Aceptación</h2><p>Al crear una cuenta, realizar una compra o utilizar CursoCapital, confirmas que has leído y aceptas estos Términos, nuestra Política de Privacidad, Política de Reembolsos y Aviso Legal. Si no estás de acuerdo, no utilices la plataforma.</p></section>
  <section><h2>2. Elegibilidad</h2><p>Debes tener al menos 18 años o la mayoría de edad legal en tu jurisdicción, o contar con autorización válida de tu padre, madre o tutor. Declaras que puedes celebrar este acuerdo y que la información proporcionada es veraz.</p></section>
  <section><h2>3. Cuenta, contraseña y seguridad</h2><p>Eres responsable de tu cuenta, de mantener la confidencialidad de tu contraseña y de toda actividad realizada bajo tus credenciales. Debes notificarnos inmediatamente cualquier acceso no autorizado. Cada cuenta es personal: está prohibido compartirla, transferirla o permitir el acceso de terceros.</p></section>
  <section><h2>4. Licencia de uso</h2><p>Tras una compra válida, CursoCapital te concede una licencia limitada, personal, revocable, no exclusiva, no transferible y no sublicenciable para acceder al contenido adquirido exclusivamente con fines educativos personales. La compra no transfiere propiedad intelectual alguna.</p></section>
  <section><h2>5. Usos prohibidos</h2><ul><li>Compartir cuentas, contraseñas, videos, archivos o enlaces protegidos.</li><li>Copiar, grabar, descargar sin autorización, redistribuir o revender contenido.</li><li>Crear obras derivadas o explotar comercialmente materiales de CursoCapital.</li><li>Eludir controles de acceso, interferir con la plataforma o automatizar extracciones.</li><li>Usar el servicio de forma ilegal, fraudulenta, abusiva o perjudicial.</li></ul></section>
  <section><h2>6. Propiedad intelectual y copyright</h2><p>La plataforma, marca, textos, videos, gráficos, metodologías, evaluaciones, descargas y demás materiales pertenecen a CursoCapital o sus licenciantes y están protegidos por leyes de propiedad intelectual y copyright. Todos los derechos no concedidos expresamente quedan reservados.</p></section>
  <section><h2>7. Conducta comunitaria</h2><p>Cuando existan funciones comunitarias, deberás actuar con respeto y abstenerte de acosar, discriminar, publicar contenido ilícito, divulgar información privada, enviar spam o suplantar identidades. Podemos moderar o retirar contenido y restringir accesos para proteger a la comunidad.</p></section>
  <section><h2>8. Pagos y reembolsos</h2><p>Los precios se muestran antes de completar la compra y los pagos se procesan mediante Stripe. Las ventas están sujetas a nuestra <a href="/refund-policy">Política de Reembolsos</a>. Eres responsable de impuestos u otros cargos aplicables.</p></section>
  <section><h2>9. Suspensión y terminación</h2><p>Podemos suspender o terminar el acceso, sin obligación de reembolso, ante fraude, contracargos indebidos, incumplimiento de estos Términos, riesgo de seguridad o conducta perjudicial. Las disposiciones sobre propiedad intelectual, responsabilidad e indemnización sobrevivirán a la terminación.</p></section>
  <section><h2>10. Disponibilidad y cambios</h2><p>No garantizamos disponibilidad ininterrumpida. Podemos realizar mantenimiento, corregir errores, actualizar contenidos, instructores, funciones o requisitos técnicos, y modificar o discontinuar partes del servicio. Procuraremos preservar el valor esencial de las compras cuando sea razonablemente posible.</p></section>
  <section><h2>11. Exclusión y limitación de responsabilidad</h2><p>CursoCapital se ofrece “tal cual” y “según disponibilidad”, en la máxima medida permitida por ley. No garantizamos resultados educativos, comerciales o financieros. En ningún caso seremos responsables por daños indirectos, incidentales, especiales, punitivos o consecuentes, lucro cesante o pérdida de datos. Nuestra responsabilidad total no excederá el importe pagado por el producto que originó la reclamación durante los doce meses anteriores.</p></section>
  <section><h2>12. Indemnización</h2><p>Aceptas defender, indemnizar y mantener indemne a CursoCapital y sus afiliados, directivos, contratistas y proveedores frente a reclamaciones razonables derivadas de tu uso indebido, tu contenido, tu incumplimiento de estos Términos o la vulneración de derechos de terceros.</p></section>
  <section><h2>13. Ley aplicable</h2><p>Estos Términos se regirán por las leyes aplicables de Estados Unidos y del estado donde CursoCapital tenga su principal establecimiento, sin perjuicio de las protecciones obligatorias que correspondan al consumidor en su jurisdicción. Las partes procurarán resolver cualquier disputa de buena fe.</p></section>
  <section><h2>14. Cambios y contacto</h2><p>Podemos actualizar estos Términos publicando una versión revisada. El uso posterior a su entrada en vigor constituye aceptación cuando la ley lo permita. Para consultas, escribe a <a href="mailto:support@cursocapital.com">support@cursocapital.com</a>.</p></section>
  </LegalPage>; }
