import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = {
  title: "Política de Privacidad",
  description: "Conoce cómo CursoCapital recopila, utiliza, protege y conserva tus datos personales.",
  alternates: { canonical: "/privacy" },
  openGraph: { title: "Política de Privacidad | CursoCapital", description: "Información sobre privacidad y protección de datos en CursoCapital." },
};

export default function PrivacyPage() {
  return <LegalPage title="Política de Privacidad" description="Esta política explica cómo CursoCapital recopila, utiliza, comparte y protege la información de quienes visitan o utilizan nuestra plataforma educativa.">
    <section><h2>1. Información que recopilamos</h2><p>Recopilamos la información necesaria para prestar nuestros servicios, administrar cuentas, procesar compras, mantener la seguridad y mejorar la experiencia. Esto puede incluir nombre, apellidos, correo electrónico, identificadores de cuenta, progreso académico, notas, marcadores, respuestas a cuestionarios y comunicaciones con soporte.</p></section>
    <section><h2>2. Información de cuenta</h2><p>Cuando creas una cuenta, tratamos los datos que proporcionas y la información asociada a tu autenticación. Eres responsable de mantener tus datos actualizados y la confidencialidad de tu contraseña.</p></section>
    <section><h2>3. Pagos y Stripe</h2><p>Los pagos son procesados de forma segura por Stripe, Inc. CursoCapital recibe datos limitados de la transacción, como estado del pago, importe, moneda, identificadores de cliente y compra, y los últimos datos descriptivos permitidos por Stripe. <strong>CursoCapital nunca almacena números completos de tarjetas de crédito, códigos de seguridad ni credenciales bancarias.</strong> Stripe trata la información de pago conforme a sus propias políticas y estándares de seguridad.</p></section>
    <section><h2>4. Cookies y tecnologías similares</h2><p>Utilizamos cookies estrictamente necesarias para autenticación, continuidad de sesión, seguridad y preferencias. También podemos usar tecnologías de medición para comprender el funcionamiento del sitio. Puedes limitar cookies desde tu navegador, aunque algunas funciones esenciales podrían dejar de operar.</p></section>
    <section><h2>5. Analítica, dispositivo y registros</h2><p>Podemos recopilar dirección IP, navegador, sistema operativo, tipo de dispositivo, idioma, páginas visitadas, referencias, marcas de tiempo y eventos técnicos. Usamos estos datos para seguridad, diagnóstico, prevención de fraude, analítica agregada y mejora del servicio.</p></section>
    <section><h2>6. Comunicaciones y marketing</h2><p>Usamos tus preferencias de comunicación para enviarte mensajes operativos sobre tu cuenta, compras, seguridad y soporte. Cuando la ley lo permita o contemos con tu consentimiento, podremos enviar novedades o contenido promocional. Puedes cancelar comunicaciones comerciales mediante el enlace incluido en ellas; los avisos transaccionales esenciales seguirán enviándose.</p></section>
    <section><h2>7. Cómo utilizamos la información</h2><ul><li>Crear y administrar cuentas y accesos.</li><li>Procesar y reconciliar compras.</li><li>Guardar progreso y personalizar la experiencia educativa.</li><li>Atender solicitudes y comunicaciones.</li><li>Prevenir fraude, abuso e incidentes de seguridad.</li><li>Cumplir obligaciones legales y hacer valer nuestros acuerdos.</li></ul></section>
    <section><h2>8. Servicios de terceros</h2><p>Podemos compartir datos limitados con proveedores que nos ayudan a operar, incluidos Supabase para autenticación y datos, Stripe para pagos, Vercel para alojamiento y proveedores de video, analítica o correo. Estos proveedores reciben únicamente lo razonablemente necesario y están sujetos a sus propios términos y obligaciones de privacidad. No vendemos tus datos personales.</p></section>
    <section><h2>9. Conservación</h2><p>Conservamos la información mientras tu cuenta esté activa y durante el tiempo necesario para prestar el servicio, mantener registros de compras, resolver disputas, prevenir fraude y cumplir obligaciones fiscales, contables o legales. Después eliminamos o anonimizamos los datos cuando sea razonablemente posible.</p></section>
    <section><h2>10. Tus derechos</h2><p>Según tu ubicación, puedes solicitar acceso, corrección, eliminación, portabilidad o limitación del tratamiento, y retirar ciertos consentimientos. Algunos datos podrán conservarse cuando exista una obligación legal o un interés legítimo prevalente. Para ejercer tus derechos, escribe a <a href="mailto:support@cursocapital.com">support@cursocapital.com</a>. Podemos verificar tu identidad antes de responder.</p></section>
    <section><h2>11. Seguridad</h2><p>Aplicamos medidas técnicas y organizativas razonables, como controles de acceso, conexiones cifradas, autenticación gestionada y limitación de privilegios. Ningún sistema es completamente infalible; debes utilizar una contraseña segura y notificarnos cualquier uso no autorizado.</p></section>
    <section><h2>12. Menores</h2><p>CursoCapital no está dirigido a menores de 13 años y no recopilamos conscientemente información de menores de esa edad. Si descubrimos que se proporcionaron dichos datos, tomaremos medidas razonables para eliminarlos.</p></section>
    <section><h2>13. Usuarios internacionales</h2><p>Nuestros servicios se operan desde Estados Unidos. Al utilizarlos desde otro país, entiendes que tus datos pueden transferirse y tratarse en Estados Unidos u otras jurisdicciones donde operan nuestros proveedores, sujetándose a las salvaguardas aplicables.</p></section>
    <section><h2>14. Cambios y contacto</h2><p>Podemos actualizar esta política para reflejar cambios legales, técnicos o comerciales. Publicaremos la versión vigente y su fecha de actualización. Para preguntas de privacidad, contáctanos en <a href="mailto:support@cursocapital.com">support@cursocapital.com</a>.</p></section>
  </LegalPage>;
}
