import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Política de Reembolsos", description: "Consulta la política de ventas finales y excepciones aplicables a las compras digitales de CursoCapital.", alternates: { canonical: "/refund-policy" }, openGraph: { title: "Política de Reembolsos | CursoCapital", description: "Condiciones de reembolso para los productos educativos digitales de CursoCapital." } };

export default function RefundPolicyPage() { return <LegalPage title="Política de Reembolsos" description="Lee cuidadosamente esta política antes de comprar. Debido a la naturaleza digital e inmediata de nuestros productos educativos, todas las ventas son finales.">
  <section><h2>Todas las ventas son finales</h2><p><strong>ALL SALES ARE FINAL. TODAS LAS VENTAS SON FINALES.</strong></p><p>CursoCapital es una plataforma educativa digital que proporciona acceso inmediato a contenido propietario. Por esa razón, todas las compras son no reembolsables. Una vez concedido el acceso, no emitiremos reembolsos, salvo cuando lo exija expresamente la ley aplicable.</p></section>
  <section><h2>Entrega del producto digital</h2><p>El producto se considera entregado cuando se activa el acceso a la cuenta. Cualquiera de las siguientes acciones confirma además la entrega y disponibilidad del producto digital:</p><ul><li>Entrar al dashboard o panel del estudiante.</li><li>Ver o comenzar a reproducir videos.</li><li>Acceder o descargar recursos, archivos o materiales.</li><li>Abrir, consultar o descargar documentos PDF.</li><li>Utilizar cuestionarios o evaluaciones.</li><li>Usar cualquier función de descarga, notas, marcadores o progreso.</li></ul></section>
  <section><h2>Casos que no califican para reembolso</h2><p>No se concederán reembolsos porque el cliente:</p><ul><li>Cambió de opinión.</li><li>No terminó el curso.</li><li>No le gustó el curso o el estilo de enseñanza.</li><li>No tuvo tiempo para utilizarlo.</li><li>No obtuvo ingresos o los resultados esperados.</li><li>No utilizó el acceso después de comprar.</li><li>No entendió el contenido o lo consideró demasiado básico o avanzado.</li><li>Olvidó cancelar, perdió sus credenciales o adquirió el producto sin revisar su descripción.</li></ul></section>
  <section><h2>Excepciones limitadas</h2><p>Solo podremos considerar una corrección o reembolso cuando exista:</p><ul><li><strong>Pago duplicado:</strong> dos cargos por el mismo producto y usuario causados por un error técnico verificable.</li><li><strong>Transacción no autorizada confirmada:</strong> después de una investigación razonable y la documentación correspondiente.</li><li><strong>Obligación legal:</strong> cuando una norma aplicable exija el reembolso.</li></ul><p>Una solicitud no garantiza aprobación. Podemos solicitar recibos, identificadores de transacción, información de la cuenta y documentación necesaria para verificarla.</p></section>
  <section><h2>Pagos duplicados</h2><p>Si observas un pago duplicado causado por un error técnico, no presentes múltiples contracargos. Escribe a <a href="mailto:support@cursocapital.com">support@cursocapital.com</a> con el correo de tu cuenta y los recibos de Stripe para que podamos investigar y corregir el cargo.</p></section>
  <section><h2>Contracargos y fraude</h2><p>Antes de iniciar una disputa bancaria, contáctanos para resolver cualquier cargo desconocido. Los contracargos fraudulentos o abusivos pueden provocar la suspensión del acceso y la presentación de evidencia de uso y entrega digital ante el procesador de pagos.</p></section>
  <section><h2>Reconocimiento del comprador</h2><p><strong>Al comprar, el cliente reconoce y acepta esta Política de Reembolsos antes de completar el pago.</strong> También reconoce que el acceso inmediato constituye el inicio de la entrega del contenido digital y que renuncia a cualquier derecho de cancelación que legalmente pueda renunciarse una vez iniciada dicha entrega.</p></section>
  <section><h2>Contacto</h2><p>Envía cualquier consulta a <a href="mailto:support@cursocapital.com">support@cursocapital.com</a>. Incluye el correo asociado a tu cuenta y el identificador de la compra.</p></section>
  </LegalPage>; }
